// Code generated by command: go run asm.go -out add.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT|NOPTR, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDQ AX, CX
	MOVQ CX, ret+16(FP)
	RET

// func Addcall(x uint64, y uint64) uint64
TEXT ·Addcall(SB), NOSPLIT, $24-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	XORQ DX, DX
	MOVQ DX, 16(SP)
	MOVQ AX, 8(SP)
	MOVQ CX, (SP)
	LEAQ ·Add+0(SB), AX
	CALL AX
	MOVQ 16(SP), DX
	MOVQ DX, ret+16(FP)
	RET
