// Code generated by command: go run asm.go -out add.s -stubs stub.go. DO NOT EDIT.

package add_call

// Adds x and y
func Add(x uint64, y uint64) uint64

// Allocate space on the stack for the return value + the two arguments
func Addcall(x uint64, y uint64) uint64
